fix compilation error in parse_range()
Due to some rebasing mishap the compilation broke with the error message:
peekpoke.c: In function ‘parse_range’:
peekpoke.c:95:12: error: ‘s’ undeclared (first use in this function)
        if (s[i++] != '[')
            ^
peekpoke.c:95:12: note: each undeclared identifier is reported only once for each function it appears in

Fix this by making the naming consistent.

(I changed the variable name while tentavily reworking the function, and
some rebasing broke the build at this commit.)

Reported-by: Thomas Kaiser